export const GET_SERVICEABLE_COUNTRY = 'GET_SERVICEABLE_COUNTRY';
export const GET_PRODUCT = 'GET_PRODUCT';
export const IS_LOADING = 'IS_LOADING';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_SELECTED_CATEGORY = 'GET_SELECTED_CATEGORY';
