export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const GET_STORES = 'GET_STORES';
export const CLEAR_STORES = 'CLEAR_STORES';
export const STORE_SUGGESTIONS = 'STORE_SUGGESTIONS';
export const GET_STORE_PRODUCTS_BY_ID = 'GET_STORE_PRODUCTS_BY_ID';
